POST http://localhost:3030/api/notes
Content-Type: application/json

{
    
    "content": "You have to ask yourself, is this Niggerlicious or is this voodo.",
    "important": true
}

###

GET http://localhost:3030/api/notes

###
GET http://localhost:3030/api/notes/rdra  

###

DELETE http://localhost:3030/api/notes/67af553084ccb69233966831

###

PUT http://localhost:3030/api/notes/67517381f4a5e7b789947f35
Content-Type: application/json

{
    
    "content": "You already know the answer, don't you?",
    "important": false
}