POST http://localhost:3030/api/notes
Content-Type: application/json

{
    
    "content": "shit goes hard as fuck! as symbian.",
    "important": false
}

###

GET http://localhost:3030/api/notes

###
GET http://localhost:3002/api/notes/2

###

DELETE http://localhost:3002/api/notes/9